# CyberBan - config.yml (complete)
general:
  enforce-ops-only: true
  broadcast-on-ban: true
  broadcast-on-mute: false
  autosave-interval-minutes: 5

storage:
  use-mysql: false
  ban-file: "bans.yml"
  mute-file: "mutes.yml"
  ipban-file: "ipbans.yml"
  history-file: "history.yml"

kick-screen:
  enabled: true
  title: "&cYou have been banned!"
  lines:
    - "&7By: &f%banner%"
    - "&7Reason: &f%reason%"
    - "&7Duration: &f%duration%"
    - ""
    - "&8Support: &bdiscord.gg/yourserver"
  use-gradient: false
  gradient:
    from: "#ff5555"
    to: "#ffdd55"

defaults:
  default-ban-duration: "perm"
  softban-duration-ms: 60000

messages:
  file: "messages.yml"

version-check:
  enabled: true
# Dont Change this otherwise your Plugin will break
  github-repo: "CyberLucx/CyberBan"
  interval-minutes: 30

logging:
  debug: false
  log-file: "cyberban.log"

prebans:
  - name: "ExamplePlayer"
    banner: "Admin"
    until: "perm"
    reason: "Example reason"

premutes:
  - name: "NoisyPlayer"
    muter: "Helper"
    until: "1h"
    reason: "Spam"

preipbans:
  - ip: "203.0.113.45"
    bis: "perm"
    grund: "Example IP ban"

kick-if-banned-online: true

gui:
  enabled: true
  rows: 3
  title: "&8CyberBan Admin"
