name: CyberBan
main: org.cyberluca.cyberBan.CyberBanPlugin
version: 2.0.3
api-version: 1.21.4
author: CyberLuca

commands:
  ban:
    description: Bannt einen Spieler.
    usage: /ban <spieler> <dauer|perm> [grund]
  unban:
    description: Entbannt einen Spieler.
    usage: /unban <spieler>
  mute:
    description: Mutet einen Spieler.
    usage: /mute <spieler> <dauer|perm> [grund]
  unmute:
    description: Entmutet einen Spieler.
    usage: /unmute <spieler>
  check:
    description: Zeigt den Ban/Mute Status eines Spielers.
    usage: /check <spieler>
  banhistory:
    description: Zeigt die Ban-Historie eines Spielers.
    usage: /banhistory <spieler>
  mutehistory:
    description: Zeigt die Mute-Historie eines Spielers.
    usage: /mutehistory <spieler>
  softban:
    description: Softbannt einen Spieler.
    usage: /softban <spieler> [grund]
  cyberbanversion:
    description: "Check for CyberBan updates"
    usage: /cyberbanversion check
  ipban:
    description: Bannt die IP eines Spielers.
    usage: /ipban <spieler|ip> <grund>
  cyberban:
    description: Admin Befehle für CyberBan.
    usage: /cyberban reload
permissions:
  cyberban.ban: { default: op }
  cyberban.unban: { default: op }
  cyberban.mute: { default: op }
  cyberban.unmute: { default: op }
  cyberban.ipban: { default: op }
  cyberban.softban: { default: op }
  cyberban.history: { default: op }
  cyberban.reload: { default: op }
